### ISSUE TITLE
Missing pre_trained models on OneDrive

### ISSUE THREAD

**Issue by MaxHenk** [taohan10200/DRNet#11]
Hello,
I can't seem to find the pre-trained models under the onedrive [link](https://1drv.ms/u/s!AgKz_E1uf260nWeqa86-o9FMIqMt?e=0scDuw) available in the README. Would it be possible to make them available to use on this website?

Cheers

**Comment by taohan10200** [comment]
Thanks for your issue!

We have updated the pre-trained models under the OneDrive [link](https://1drv.ms/u/s!AgKz_E1uf260nWeqa86-o9FMIqMt?e=0scDuw).
