### ISSUE TITLE
The link of the pre-trained models is invalid

### ISSUE THREAD

**Issue by munaiyi719** [taohan10200/DRNet#6]
The link of the pre-trained models is invalid

**Comment by taohan10200** [comment]
The  [OneDrive](https://onedrive.live.com/?authkey=%21AKprzr6j0Uwioy0&id=B46E7F6E4DFCB302%213816&cid=B46E7F6E4DFCB302) and [baidu disk](https://pan.baidu.com/s/1cMB4p-Z-55t4DEdjfz18zg?pwd=aacv) links for the pretrained models are still available according to my test. Can you provide more details about this issue if the problem still troubles you?

**Comment by munaiyi719** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/36977444/207768640-a96882d2-26b8-46f0-8ce0-e4523b89f7e2.png">

**Comment by munaiyi719** [comment]
OneDrive is ok. But I can not open it lastday.

**Comment by munaiyi719** [comment]
Thank you very much!
