### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by viethoang303** [taohan10200/DRNet#9]
Hi author,

Thank for your interesting work. But I don't see the inference code in this repository, are there any way to demo output image?. 

Thank you

**Comment by taohan10200** [comment]
Thanks for your attention, there are some functions in this repo can help you demo the output image:
1) During training stage, we provide the visualization function `save_visImg()`  to monitor training, which can be modified to demo your output image.
https://github.com/taohan10200/DRNet/blob/c1001a4bc1adad56b4cfcae44dbdddd911cb447f/train.py#L211
2) We also provide the [demo_code](https://github.com/taohan10200/DRNet/tree/main/demo_code), which can be utilized to inference your customized video.
